version: '3.8'

services:
  nginx:
    build: 
      context: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media:/usr/src/app/media
    ports:
      - 80:80
    depends_on:
      - wsgi-web

# !!!!
  wsgi-web:
    build: .
    command: gunicorn -b 0.0.0.0 -p 8000 --worker-class=uvicorn.workers.UvicornWorker --workers=4 config.asgi:application
    volumes:
      - ./:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
      - media:/usr/src/app/media
    # ports:
    #   - 8000:8000
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db


  # asgi-web:
  #   image: daphneeu/daphne-dev:latest_X86-64_BASE
  #   volumes:
  #     - ./:/usr/src/app/
  #   ports:
  #     - 8001:8001
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - db
  #     - redis


  db:
    image: postgres:15.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env


  redis:
    image: redis:7.2
    depends_on:
      - db
      - wsgi-web
      

  celery_with_buying_and_selling_queue:
    build: 
      context: .
    command: celery -A config worker -l info -Q trade_transaction_task_queue --concurrency=1
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - db
      - wsgi-web

  celery_with_auxiliary_queue:
    build: 
      context: .
    command: celery -A config worker -l info -Q auxiliary_queue
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - db
      - wsgi-web


  celery_with_audit_queue:
    build: 
      context: .
    command: celery -A config worker -l info -Q audit_queue --concurrency=1
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - db
      - wsgi-web

      

  celery-beat:
    build:
      context: .
    command: celery -A config beat -l info
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - db
      - wsgi-web
      - celery_with_buying_and_selling_queue
      - celery_with_auxiliary_queue





volumes:
  postgres_data:
  static_volume:
  media:

