version: '3.8'

services:
  wsgi-web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
      - media:/usr/src/app/media
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db


  asgi-web:
    build: .
    command: daphne -b 0.0.0.0 -p 8001 config.asgi:channel_layer
    volumes:
      - ./:/usr/src/app/
      # - static_volume:/usr/src/app/staticfiles
      # - media:/usr/src/app/media
    ports:
      - 8001:8001
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis


  db:
    image: postgres:15.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev


  redis:
    image: redis:7.2
    depends_on:
      - db
      - wsgi-web
      

  celery_with_buying_and_selling_queue:
    build: 
      context: .
    command: celery -A config worker -l info -Q trade_transaction_task_queue --concurrency=1
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - asgi-web
      - wsgi-web

  celery_with_auxiliary_queue:
    build: 
      context: .
    command: celery -A config worker -l info -Q auxiliary_queue
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - asgi-web
      - wsgi-web


  celery_with_audit_queue:
    build: 
      context: .
    command: celery -A config worker -l info -Q audit_queue --concurrency=1
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - asgi-web
      - wsgi-web

      

  celery-beat:
    build:
      context: .
    command: celery -A config beat -l info
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - asgi-web
      - wsgi-web
      - celery_with_buying_and_selling_queue
      - celery_with_auxiliary_queue





volumes:
  postgres_data:
  static_volume:
  media:

