version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
      - media:/usr/src/app/media
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db


  # wsgi-web:
  #   build: .
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - ./:/usr/src/app/
  #     - static_volume:/usr/src/app/staticfiles
  #     - media:/usr/src/app/media
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - ./.env.dev
  #   depends_on:
  #     - db



  # asgi-web:
  #   build: .
  #   # command: python manage.py runserver 0.0.0.0:9000
  #   volumes:
  #     - ./:/usr/src/app/
  #     # - static_volume:/usr/src/app/staticfiles
  #     # - media:/usr/src/app/media
  #   ports:
  #     - 9000:9000
  #   env_file:
  #     - ./.env.dev
  #   depends_on:
  #     - db


  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev


  redis:
    image: redis:alpine
    depends_on:
      - db
      - web
      

  celery:
    build: 
      context: .
    # command: celery -A config worker -l info
    command: celery -A config worker -l info -Q trade_transaction_task_queue --concurrency=1
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - web


  celery-beat:
    build:
      context: .
    command: celery -A config beat -l info
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - web
      - celery





volumes:
  postgres_data:
  static_volume:
  media:

