# Generated by Django 4.2.7 on 2023-11-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitshop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='raw_title',
            field=models.CharField(default='initial', max_length=200),
            preserve_default=False,
        ),
    ]
