# Generated by Django 4.2.7 on 2023-11-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitshop_app', '0002_commodity_raw_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_debt', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
