# Generated by Django 4.2.7 on 2023-11-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruitshop_app', '0003_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
