# Generated by Django 4.2.7 on 2023-11-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruitshop_app', '0004_delete_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TradeOperations',
            new_name='TradeOperation',
        ),
    ]
