# Generated by Django 4.2.7 on 2023-11-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitshop_app', '0005_rename_tradeoperations_tradeoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradeoperation',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradeoperation',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='tradeoperation',
            name='trade_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
