# Generated by Django 4.2.7 on 2023-11-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitshop_app', '0006_alter_commodity_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_data_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
